## <center>Elements Of Data Science - F2024</center>
# <center>Week 2: Python Intro/Review and Numpy<center>
### <center>9/15/2024</center>

# TODOs

- **Review** Selections from PDSH Chapter 2
- **Read** Selections from PDSH Chapter 3
- **Skim** Selections from PDSH Chapter 4
<br>
 
- Complete Week 2 Quiz (Due 1 week from today, Sep 22 @11:59pm)

### Announcements 
**Office hours** 
- Monday 6pm-6:50pm, location: DSI Conference room
- Skype, by appointment only, Tuesdays 6pm+. (link to be sent once OH requested)

# TODOs

- Ch 2. Introduction to NumPy
    - Understanding Data Types in Python
    - The Basics of NumPy Arrays
    - <span style="color:gray;">Skim:</span> Computation on NumPy Arrays: Universal Functions
    - Aggregations: Min, Max, and Everything In Between
    - <span style="color:gray;">Skim:</span> Computation on Arrays: Broadcasting
    - Comparisons, Masks, and Boolean Logic
    - Fancy Indexing
    - Sorting Arrays
    - <span style="color:gray;">Structured Data: NumPy's Structured Arrays</span>

# TODOs

- Ch 3. Data Manipulation with Pandas
    - Introducing Pandas Objects
    - Data Indexing and Selection
    - <span style="color:gray;">Operating on Data in Pandas</span>
    - Handling Missing Data
    - <span style="color:gray;">Hierarchical Indexing</span>
    - Combining Datasets: Concat and Append
    - <span style="color:gray;">Combining Datasets: Merge and Join</span>
    - Aggregation and Grouping
    - <span style="color:gray;">Pivot Tables</span>
    - <span style="color:gray;">Skim:</span>Vectorized String Operations
    - <span style="color:gray;">Working with Time Series</span>
    - <span style="color:gray;">High-Performance Pandas: eval() and query()</span>

# TODOs

- Ch 4. Visualization with Matplotlib
    - Simple Line Plots
    - Simple Scatter Plots
    - <span style="color:gray;">Visualizing Errors</span>
    - <span style="color:gray;">Density and Contour Plots</span>
    - <span style="color:gray;">Histograms, Binnings, and Density</span>
    - <span style="color:gray;">Customizing Plot Legends</span>
    - <span style="color:gray;">Customizing Colorbars</span>
    - Multiple Subplots
    - <span style="color:gray;">Text and Annotation</span>
    - <span style="color:gray;">Customizing Ticks</span>
    - <span style="color:gray;">Customizing Matplotlib: Configurations and Stylesheets</span>
    - Three-Dimensional Plotting in Matplotlib
    - <span style="color:gray;">Geographic Data with Basemap</span>
    - Visualization with Seaborn


## Getting Changes from Git
<br>

1. `cd` to the cloned class repostory
2. `git pull`
<br>

example:
```terminal
$ cd ~/proj/eods-f24
$ git pull
```

<br>
<br>

# <center>Questions?</center>
<br>
<br>


# TODAY
<br>

- Tools Review

- Getting "Help" Documentation

- Python (Review?)

- Numpy

# Tools Review

- Starting Jupyter
- Notebooks, Kernels and Virtual Environments

# Getting "Help" Documentation in Python

In [1]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



# Class note
## help (Function) ==> it gives you the documentation of the function and its arguments
## help (numpy) ==> it gives you the documentation of the numpy library
## use print? to get the source code of the function and indicate what function it is
## use print?? to get the source code of the function and indicate what function it is and what it does

Also, in ipython/jupyter:

```terminal
print?            # show docstring
print??           # show code as well
print([SHIFT+TAB] # get help in a popup
```

# Python (Review?)

- Whitespace Formatting
- Dynamic Typing
- Basic Data Types
- Functions
- String Formatting
- Exceptions and Try-Except
- Truthiness
- Comparisons and Logical Operators
- Control Flow
- Assert
- Sorting
- List/Dict Comprehensions
- Importing Modules
- collections Module
- Object Oriented Programming

# Whitespace Formatting

- Instead of braces or brackets to delimit blocks, use whitespace

```python
# The pound sign marks the start of a comment. Python itself
# ignores the comments, but they're helpful for anyone reading the code.
for i in [1, 2, 3, 4, 5]:
    print(i)                    # first line in "for i" block
    
    for j in [1, 2, 3, 4, 5]:
        
        print(j)                # first line in "for j" block
        print(i + j)            # last line in "for j" block
    print(i)                    # last line in "for i" block
print("done looping")
```
<br>

- 4 space indentations are conventional
- Style Guide : PEP 8 (https://www.python.org/dev/peps/pep-0008/)

# Dynamic Typing

- don't need to specify type at variable creation (though they'll get one at runtime)

In [128]:
x = 3
x = 3.14
x = 'apple'
x

'apple'

# Class note
## python will infer the last line of a code block as the output if it is not explicitly printed.
## we need to specify the output variable if we want to capture the output of a code block such as assigning x, y, z.

In [129]:
# to determine the current variable type
type(x)

str

# Basic Python Data Types

- **int** (integer): `42`

- **float** : `4.2`, `4e2`

- **bool** (boolean): `True`, `False`

- **str** (string) : `'num 42'`, `"num 42"`,\
`"""multi-line
string"""`

- **None** (null): `None`
<br>

- also `long`, `complex`, `bytes`, etc.

# Functions

In [130]:
def add_two(x):
    """Adds 2 to the number passed in."""
    return x+2


add_two(2)

4

In [131]:
help(add_two)

Help on function add_two in module __main__:

add_two(x)
    Adds 2 to the number passed in.



Reminder, also in ipython/jupyter:

  - `add_two?            # show docstring`
  - `add_two??           # show code as well`
  - `add_two([SHIFT+TAB] # get help in a popup`

# Function Arguments

- **positional arguments** must be entered in order

In [132]:
def subtract(x,y):
    return x-y

subtract(3,1)

2

- **keyword arguments** must follow positional 
- can be called in any order

In [133]:
def proportion(numer,denom,precision=2):
    return round(numer/denom,precision)

proportion(2,precision=2,denom=3)

0.67

# class note
## positional arguments must be followed by keyword arguments: def func(a, b, c=0, d=1): where a, b are positional arguments and c, d are keyword arguments with default values.

# String Formatting

In [134]:
x = 3.1415

# str(x) will convert the value of x to a string

'the value of x is ' + str(x)

'the value of x is 3.1415'

In [135]:
'the value of x is %0.2f' % x

# %0.2f is a format specifier that formats the value of x as a float with 2 decimal places.

'the value of x is 3.14'

In [136]:
'the value of x is {:0.10f} and not {}'.format(x, 10)

# {:0.10f} formats the float x with 10 decimal places and pads it with zeros on the left if necessary.
# format(x, 10) indicates that the second argument is not a format specifier, but a second argument to be inserted into the string.

'the value of x is 3.1415000000 and not 10'

In [137]:
f'the value of x is {x:0.2f}'
# note: f-string is a literal string, prefixed with 'f', which contains expressions inside braces.
# f'expression + {numerical expression}' => use f'' string format to insert the numerical expression into the string.

'the value of x is 3.14'

- often want to print variable values for debugging

In [138]:
f'x = {x:0.2f}'

'x = 3.14'

In [139]:
f'{x = :0.2f}' # new in python3.8

'x = 3.14'

# String Formatting Cont.

In [140]:
"""This is a multiline string.
The value of x is {}.""".format(x)

# /n indicates the original line should be continued on the next line.

'This is a multiline string.\nThe value of x is 3.1415.'

In [141]:
print("""This is a multiline string.
The value of x is {}.""".format(x))

# add print statement can return more systematic format into 2 lines of output

This is a multiline string.
The value of x is 3.1415.


- to learn more https://realpython.com/python-string-formatting/

# Python Data Types Continued: `list`

In [142]:
# elements of a python list do not all have to be of the same type
x = [42,'e',2.0]
x

[42, 'e', 2.0]

In [143]:
x[0] # indexing

# [0] is the first element of the array x.

42

In [144]:
x[-1] # reverse indexing

# [-1] means the last element of the array.

2.0

In [145]:
x[2] = 4 # assignment
x

# x[index] = value => value change in the list at the specified index

[42, 'e', 4]

In [146]:
x.append('a') # add a value to list
x

# list.append("number / string / boolean") indicates the method to add a value to the end of the list.

[42, 'e', 4, 'a']

In [147]:
value_at_1 = x.pop(1) # remove/delete at index
x

# list.pop(index) indicates the index of the element to be removed and returns the value of the removed element.

[42, 4, 'a']

# Python Data Types Continued: `dict` (Dictionary)


- Stores key:value pairs

In [148]:
x = {'b':[2,1],'a':1,'c':4} 
# or x = dict(b=2,a=1,c=4)
x

# dict format use {key: value}, where key is a string and value can be any type of object and value can a list of objects and a single value

{'b': [2, 1], 'a': 1, 'c': 4}

In [149]:
# index into dictionary using key
x['b'] 

# x['key'] indicates the 'key' plays as an index to access the value in the dictionary x.

[2, 1]

In [150]:
# assign a value to a (new or existing) key
x['d'] = 3 
x

# x['new_key'] = new_value => assign a new key and value to the dictionary x

{'b': [2, 1], 'a': 1, 'c': 4, 'd': 3}

In [151]:
# remove/delete
# can specify a return a value if key does not exist (here it's None), otherwise throws an exception
x.pop('eods', None) 

# dic.pop(del_key, default_value) indicates that if the key del_key is not in the dictionary, return default_value instead of raising a KeyError.
## Here, since 'eods' is not in the dictionary, it will return None and present the dictionary without 'eods' key.

In [152]:
x

{'b': [2, 1], 'a': 1, 'c': 4, 'd': 3}

In [153]:
x.pop('d', None)

# dict.pop(key, default=None) indicates that if the key is not found in the dictionary, it will return the default value (None in this case).
# However, if the key is found, the value associated with the key will be removed from the dictionary and returned.

3

# Python Data Types Continued: `dict` Cont.


In [154]:
# using the same dictionary
x

{'b': [2, 1], 'a': 1, 'c': 4}

In [155]:
# get a set of keys
x.keys()

# dict.key() => it returns the keys in the dictionary

dict_keys(['b', 'a', 'c'])

In [156]:
# get a set of values
x.values()

# dict.values() => it returns the values in the dictionary

dict_values([[2, 1], 1, 4])

In [157]:
# get a set of (key,value) tuples
x.items()

# dict.items() => returns a view object that contains all the (key,value) tuples in the dictionary.

dict_items([('b', [2, 1]), ('a', 1), ('c', 4)])

In [158]:
# get a list of (key,value) pairs
list(x.items())

# list(dict.items()) => it convert the dict into a list of (key,value) pairs

[('b', [2, 1]), ('a', 1), ('c', 4)]

In [159]:
# create dict of mid-term and final grades
grades = {'a': [90, 100], 'b': [80, 90], 'c': [70, 80], 'd': [60, 70], 'f': [0, 60]}

# query the grades dictionary for the mid-term grades of student 'a'
grades['a'][0]  # 90
# grades['a'] indicates I need to values according to the mid-term and final grades of student 'a'
# use [0] indicates I want to know the mid-term grade of student 'a'

90

In [160]:
# what if we embed dicts inside the dict?

grades = {"a": {90: 100},"b": {80: 90}, "c": {70: 80}, "d": {60: 70}, "f": {0: 60}}

# query the final grade for "a"
grades["a"][90] # output: 100

# this time, grades["a"] induces the dict {90: 100} as value
# [90] plays a key indexing to access the value 100

100

In [161]:
grades.pop('a', None)
# we want to delete the key 'a' from the dictionary if it exists, but if it doesn't exist, we don't want to raise an error.

{90: 100}

In [162]:
grades

{'b': {80: 90}, 'c': {70: 80}, 'd': {60: 70}, 'f': {0: 60}}

# Python Data Types Continued: `tuple`

- like a list, but **immutable**

In [163]:
x = (2,'e',3,4)
x

# inside the tuple, you cannot either change the value of the elements nor add or remove elements from the tuple.

(2, 'e', 3, 4)

In [164]:
x[0] # indexing

# tuple indexing is like list indexing, but with parentheses instead of square brackets

2

In [165]:
x[0] = 3 # assignment? Nope, error: immutable`

# tuple cannot be modified

TypeError: 'tuple' object does not support item assignment

In [63]:
# we cannot add or remove the element from tuple using the pop() method.

x.remove(2)
print(x)

AttributeError: 'tuple' object has no attribute 'remove'

In [64]:
# tuple with list inside
a = (1,2,[10,12])
print(a)

(1, 2, [10, 12])


In [65]:
# we can modify the elements inside the list even if it is in the tuple

a[2][0] =15 # modify the first element of the second list in the tuple

# a[2] will induce the second list in the tuple [10, 12]
# a[2][0] means we want to change the first element inside the list to be 15

print (a)

(1, 2, [15, 12])


In [58]:
# we can also add or remove any value inside the list by appending or removing elements from the list inside the tuple.
a[2].append(10)


In [59]:
a

(1, 2, [15, 12, 10])

In [73]:
# If there is tuple inside the list, we can add and remove the tuple but cannot change the element inside the tuple.

b = [1, (2,'e',3,4), 8, 9]
b.pop(1) # remove the tuple (2,'e',3,4)

# b.pop(1) induce the second element of the list to be removed, which is the tuple (2,'e',3,4)
# it returns the tuple to be removed

(2, 'e', 3, 4)

In [74]:
b.append((10,11)) # add a tuple (10,11) to the list
print(b)

[1, 8, 9, (10, 11)]


# Python Data Types Continued: `set`

## Set is the **collection of unique elements in Python**. It is an unordered collection of elements that can be of any data type. Sets are useful for performing mathematical operations like union, intersection, and difference.

In [75]:
lst = [1,1,1,1,1,1,5,5,'Jack']
lst = list(set(lst))

# set(lst): using set() method, we can remove all the duplicates from the list.
# list(set(lst)): convert the set back to a list.

In [77]:
lst

['Jack', 1, 5]

In [78]:
# set expression
x = {2,'e','e'} # or set([2,'e','e'])
x

{2, 'e'}

In [79]:
# we can insert a new element into the set using the add() method.
x.add(1) # insert
x

{1, 2, 'e'}

In [80]:
# we can also remove the element from the list using the remove() method.
x.remove('e') # remove/delete
x

{1, 2}

In [81]:
# set operation: intersection
x.intersection({2,3})
# it means that we want to take the intersection of set x and set {2,3}
# set x is {1,2}

{2}

In [82]:
# set operation: difference
x.difference({2,3})
# we want to find the elements in set x that are not in set {2,3}
# set x is {1,2} and {1} is not in set {2,3}

{1}

In [83]:
x[0] # cannot index into a set
# we cannot treat set as list for indexing

TypeError: 'set' object is not subscriptable

# Determining Length with `len`

In [84]:
len([1,2,3])
# len(list) returns the number of elements in the list

3

In [85]:
len({'a':1,'b':2,'c':3})
# len(dict) returns the number of key-value pairs in the dictionary.

3

In [56]:
len('apple')
# len(string) returns the length of the string in characters.

5

# Exceptions

In [87]:
'a' + 2
# since 'a' and 2 are not of the same type, Python will raise a TypeError.

TypeError: can only concatenate str (not "int") to str

## Common exceptions:
- SyntaxError
- IndentationError
- ValueError
- TypeError
- IndexError
- KeyError
- and many more https://docs.python.org/3/library/exceptions.html

# Catching Exceptions with `try`-`except`

## Syntax Error
### When Python detects invalid syntax in your code before execution. It is raised when the code cannot be parsed correctly.

In [89]:
try:
    eval('x === y')  # Invalid syntax
except SyntaxError:
    print("There's a syntax error!")

There's a syntax error!


## IndentationError
### When there’s an incorrect indentation (e.g., inconsistent use of tabs and spaces or missing indentation)

In [98]:
try:
    exec('def my_func(): \nprint("Hello")')  # Missing indentation (it should be \n print)
except IndentationError:
    print("There is an indentation error!")

## ValueError
### When a function receives an argument of the correct type but an invalid value.

In [105]:
try:
    int('abc')  # Cannot convert 'abc' to an integer (it should be int('123'))
except ValueError:
    print("There was a ValueError!")

There was a ValueError!


## TypeError
### When an operation or function is applied to an object of inappropriate type.

In [106]:
try:
    'a' + 2 # Cannot add a string and an integer (it should be 'a' + str(2))
except TypeError as e:
    print(f"We did this on purpose, and here's what's wrong:\n{e}")

We did this on purpose, and here's what's wrong:
can only concatenate str (not "int") to str


## IndexError
### when you try to access an index in a list or other sequence that doesn’t exist.

In [107]:
try:
    my_list = [1, 2, 3]
    print(my_list[5])  # Index 5 doesn't exist
except IndexError:
    print("Index out of range!")

Index out of range!


## KeyError
### when a dictionary key is not found in the dictionary.

In [108]:
try:
    my_dict = {'a': 1, 'b': 2}
    print(my_dict['c'])  # 'c' key doesn't exist
except KeyError:
    print("Key not found!")

Key not found!


In [109]:
# we can loop through except arguments to catch specific errors
try:
    set([1,2,3])[0]
except SyntaxError as e:
    print(f"Print this if there's a syntax error")
except Exception as e:
    print(f"Print this for any other error")

Print this for any other error


# Truthiness

- boolean: `True`, `False`
<br>

- These all translate to `False`:
 - `None`
 - `[]` (empty list)
 - `{}` (empty dictionary)
 - `''` (empty string)
 - `set()`
 - `0`
 - `0.0`

# Comparison Operators

- equality: `==`
- inequality: `!=`

In [110]:
3 == 3 # == indicate the equality

True

In [61]:
3 != 4

True

 - less than: `<`
 - greater than: `>`
 - '(less than/greater than) or equal to:  `<=` , `>=`

In [62]:
3 > 4

False

# Logical Operators

- logical operators: `and`, `or`, `not`

In [111]:
( (3 > 5) or ((3 < 4) and (5 > 4)) ) and not (3 == 5)

# (True or (False and True)) and not (True)
# (1 or (0 and 1)) and not (1)
# 1 and 0 => 1 => True

# "True" as 1 and "False" as 0, 
# "or" as addition, "and" as multiplication
# "not" as negation.

True

- `any()`: at least one element is true

In [113]:
any([0,0,0])
# any(list) returns True if any element in the list is True, otherwise False.

False

In [114]:
any([1,0,0])
# since there is at least one 1 in the list, the output is True.

True

- `all()`: all elements are true

In [115]:
all([True,1,False])
# all(list) returns True if all elements in the list are True, otherwise False.

False

In [116]:
all([True,1,True])
# since none of elements are False, the output is True

True

- **bitwise operators** (we'll see these in numpy and pandas) : `&` (and), `|` (or), `~` (not)

# Assert

- use `assert` to test anything we know should be true
- simple unit test
- raises exception when assertion is false, otherwise nothing

## assert statement can check the output of a function or expression. If the output is not as expected, the program will raise an AssertionError.

### format: **assert expression / function, 'error message'**

In [117]:
assert 2+2 != 4
# since "2 + 2 is not equal to 4" is not true, the assertion will output an error message.

AssertionError: 

In [118]:
assert 1 == 0, 'if this is wrong what you want to display'

AssertionError: if this is wrong what you want to display

In [119]:
# can add an error message
assert 1 == 0, "1 does not equal 0"

AssertionError: 1 does not equal 0

In [121]:
assert 1 == 1 # no assertion error when the expression is true

# Control Flow: `if`, `elif`, `else`

- `if` then `elif` then `else`

In [69]:
x = 3
if x > 0:
    print('x > 0')
elif x < 0:
    print('x < 0')
else:
    print('x == 0')

x > 0


- single-line `if` then `else`

In [70]:
print("x < 0") if (x < 0) else print("x >= 0")
# print (expression 1) if (condition for expression 1 is true) else print (expression 2)

x >= 0


# More Control Flow: `for` and `while`

## for loop: it can iterate over a sequence of values, such as a list or a string.
- use for loop when you want to repeat a set of instructions for **a fixed number of times**.
- `for` each element of an iterable: do something
- use `for` loop when you are iterating over a **sequence of values** and you want to perform the same operation on each element.

In [122]:
a = []
for x in [0,1,2]: # iterate over each element in the list [0, 1, 2]
    a.append(x) # append each element to the list a
a

# the loop stops automatically when it reaches the end of the list
# The list a contains all the elements of [0, 1, 2]

[0, 1, 2]

### while loop: it can run indefinitely until the condition is no longer true.
- `while` something is true
- `while` executes as long as a specified condition is true.
- use `while` loop when **the number of iterations is unknown** or **when the loop should continue until a certain condition is met**

In [127]:
x = 0
while x < 3: # it will continue looping until x is less than 3
    x += 1 # starting from x = 0, it will add 1 to x in each iteration, so x will be 1, 2, 3, and when x reaches to 3, the loop will stop due to it loop task is done
x

3

# More Control Flow: `break` and `continue`

## 'break' statement
- `break` : break out of current loop
- the loop exits the loop entirely once the cetain condition is met and continues with the next statement after the loop.

In [130]:
x = 0
while True: # infinite loop due to condition is true always
    x += 1
    if x == 10:
        print(x)
        break # once x = 10 by incrementing to be true, and loop will print 10 and exits using break

10


### `continue` : continue immediately to next iteration of loop
- `continue` statement is used to skip the current iteration of the loop and move to the next iteration.
- It is used when we want to **skip the current iteration** and **move to the next iteration**, but the current **remaining statements in the loop cycle** will not be executed 
- it skips the rest of current iteration and moves to the next iteration of the loop

In [74]:
for name in ['John', 'Ben', 'Julia']:
    if name == 'Ben': 
        continue # once the expression is met, the loop will skip to the next iteration without executing the rest of the code block
    print(name)
    

# when the loop reaches 'Ben', it will skip to the next iteration and print 'Julia' instead.
# John and Julia are printed since  the continue statement is not met for them.

John
Julia


In [75]:
for x in range(5): # for loop iterates over range 0 to 4 (inclusive)
    if x == 1:
        continue
    print(x)
    
# when x == 1, the continue statement skips the rest of the loop and moves on to the next iteration.
# all values of x will be printed except for 1.

0
2
3
4


# Generate a Range of Numbers: `range`

In [1]:
# create list of integers from 0 up to but not including 4
a = []
for x in range(4): # range(4) is exclusive, so we need to use 4-1=3
    a.append(x)
a

# range(4) = range(0,4), starting from 0 to 3 (exclusive)

[0, 1, 2, 3]

In [2]:
range(4)

range(0, 4)

In [3]:
list(range(4))

[0, 1, 2, 3]

In [4]:
list(range(3,5)) # with a start and end+1
# start from the third element (index 2) and go up to the fifth element (index 4) => [0, 1, 2, 3 (third element), 4 (fifth element)]

[3, 4]

In [80]:
list(range(0,10,2)) # with start, end+1 and step-size
# start from first element (index 0) and end at the 10th element (index 9) with a step-size of 2 => [0(first element), 1(skip odd index), 2, 3, 4, 5， 6, 7， 8， 9]

[0, 2, 4, 6, 8]

# Keep track of list index or for-loop iteration: `enumerate`
## to add an index counter to the iterable (list, tuple, etc.)
## and to return both index and items in each iteration of a loop.

In [81]:
for i,x in enumerate(['a','b','c']): # enumerate() requires both i, x where i is the index counter and x is the value of the list
    print(i,x) # in each iteration, i is the index and x is the value of the list

0 a
1 b
2 c


In [82]:
list(enumerate(['a','b','c']))
# convert enumerate object to list => [(index counter, element), (index counter, element), (index counter, element)]

[(0, 'a'), (1, 'b'), (2, 'c')]

# Sorting

Two ways to sort a list:

1. by changing the list itself: `list.sort()`
- This method sorts the list in place, meaning it modifies the original list but does not create a new list.
- The `list.sort()` method sorts the list in ascending order by default.
- To sort the list in descending order, you can use the `reverse=True` parameter.

In [7]:
x = [4,1,2,3]
x.sort() # => it will return the order in ascending order
assert x == [1,2,3,4], 'Not same lists' # assert statement to check if the sorted list is the same as the original list

2. without changing the list: `sorted(list)`
- `sorted()` function **returns a new sorted list without changing the original list.**
- `sorted(list)` sorts the list in **ascending order**.
- `sorted(list, reverse=True)` sorts the list in descending order.
- `sorted(list)` can work on **any iterable object**, such as strings, tuples, and dictionaries.

In [8]:
x = [4,1,2,3]
y = sorted(x)
assert x == [4,1,2,3]
assert y == [1,2,3,4]

# Sorting Cont.

- To sort descending, use `reverse=True`:

In [9]:
assert sorted([1,2,3,4], reverse=True) == [4,3,2,1]

- Pass a `lambda` function to 'key=' to specify what to sort by:

In [11]:
# for example, to sort a dictionary by value
d = {'a':3,'b':5,'c':1}

# recall that .items() returns a set of key,value tuples
s = sorted(d.items(), key=lambda x: x[1])
# sorted() method will sort the list of tuples by the second element of each tuple (i.e. the value)
# dict.items() will return a list of tuples, so we can use a lambda function to sort by the second element of each tuple
# the lambda function takes a tuple x and returns x[1], which is the value of the dictionary item
## for ('a', 3), lambda x: x[1] returns 3
## for ('b', 5), lambda x: x[1] returns 5
## for ('c', 1), lambda x: x[1] returns 1

assert s == [('c', 1), ('a', 3), ('b', 5)] # we use sorted() method to order the list of tuples by value in ascending order, the ordered tuples will be ascending by values

In [12]:
sorted(d.items(), key=lambda x: x[0])
# since this time we use lambda function to sort the dictionary by keys in x[0], the output will be sorted by keys in ascending order.

[('a', 3), ('b', 5), ('c', 1)]

# List Comprehensions

## Syntax: [expression for item in iterable if condition]
- expresssion: this is result or operation performed on each item in the iterable
- for item in iterable: this is the loop that iterates over each item in the iterable
- if condition: this is an optional condition that filters the items in the iterable

- Like a single line for loop over a list or other iterable

In [13]:
# which integers between 0 and 3 inclusive are divisible by 2?
is_even = []
for x in range(0,4):
    is_even.append(x%2 == 0)
is_even

[True, False, True, False]

In [14]:
[x%2 == 0 for x in range(0,4)] # using a list comprehension

[True, False, True, False]

In [15]:
# what are the indices of the vowels in 'apple'?
vowels = ['a','e','i','o','u']
[i for i,x in enumerate('apple') if x not in vowels]

[1, 2, 3]

In [17]:
# using both for and if-else condition without list comprehension
a = []
for x in range(5):
    if x % 2 == 0:
        a.append(x * 2)
    else:
        a.append(x)
print(a)

[0, 1, 4, 3, 8]


In [19]:
# use the same condition in list comprehension
a = [x * 2 if x % 2 == 0 else x for x in range(5)]
print (a)

[0, 1, 4, 3, 8]


# Dictionary Comprehension
## syntax: {key_expression: value_expression for item in iterable if condition}
- key_expression: expression that generates the key for the dictionary
- value_expression: expression that generates the value for the dictionary
- iterable: an iterable object (e.g. list, tuple, set, etc.)
- for item in iterable: iterates over each item in the iterable
- if condition: optional condition that must be True for the item to be included in the dictionary

- list comprehension but for (key,value) pairs
- can add logic to dictionary creation

In [21]:
pairs = [(1,'e'),(2,'f'),(3,'g')]

In [22]:
dict(pairs)

{1: 'e', 2: 'f', 3: 'g'}

In [23]:
# modify value and only include odd keys
{key:'value_'+ val for key,val in pairs if key%2 == 1} # it will return the key with value that fits the if condition

{1: 'value_e', 3: 'value_g'}

In [24]:
# Creating a Dictionary from Two Lists

keys = ['a', 'b', 'c']
values = [1, 2, 3]

combined_dict = {k: v for k, v in zip(keys, values)}
print(combined_dict)

{'a': 1, 'b': 2, 'c': 3}


In [26]:
# traditional for loop with dictionary
even_squares = {}
for x in range(1, 6): # iterate over numbers 1 to 5
    if x % 2 == 0: # x is key in even_squares dictionary
        even_squares[x] = x**2 # even_squares[x] indicate when if-condition is true, add x^2 as value to even_squares dictionary where key is x

print(even_squares)

{2: 4, 4: 16}


In [28]:
# Alternatively, we can use dict comprehension to achieve the same result:

even_squares = {x: x**2 for x in range(1, 6) if x % 2 == 0}
# x: x**2 indicate the key and value expression in the dict to be returned.
# range(1, 6) is the range of numbers to be used as keys => in this case, x is the key.
# if x % 2 == 0 is the condition to filter out odd numbers. If the condition is True, the value will be squared and added to the dictionary.

print(even_squares)

{2: 4, 4: 16}


# Iterables and Generators

- **Iterable**: anything we can iterate over, eg list

- **Iterator**:
    - the object doing the iterating
    - can use `.next()` to get the next value in the iterable
    - every iterator is an iterable, but reverse not always true

In [29]:
iter_obj = iter([1,2,3])

assert next(iter_obj) == 1

# Iterables and Generators Cont.

- **Generator**
 - generates values *lazily* on demand (values not stored in memory)
 - contains a `yield` operator
 - can use `.next()` to get the next value
 - or wrap in comprehension or list to generate all

In [95]:
def generate_ones(n):
    i = 0
    while i < n:
        yield 1
        i += 1

assert list(generate_ones(3)) == [1,1,1]

# Object Oriented

In [96]:
class MyClass:
    """A descriptive docstring."""
    
    # constructor
    def __init__(self,myvalue = 0):  # what happens when created
        # attributes
        self.myvalue = myvalue

    def __repr__(self):   # what gets printed out (string repr.)
        return f'MyClass(myvalue={self.myvalue})'

    # any other methods
    
    def get_value(self):
        """Return the value in myvalue."""
        return self.myvalue

In [97]:
x = MyClass(100)            # instantiate object

assert x.myvalue == 100     # access object attribute

assert x.get_value() == 100 # use object method

# Importing Modules
<br>

- Want to import a module/library? Use `import`

In [98]:
import math

math.sqrt(2)

1.4142135623730951

- Want to import a submodule or function from a module? Use `from`

In [99]:
from math import sqrt,floor

print(sqrt(2))
print(floor(sqrt(2)))

1.4142135623730951
1


# Importing Modules Cont.
<br>

- Want to import a module using an alias? Use 'as'

In [100]:
import math as m
m.sqrt(2)

1.4142135623730951

- Don't do: `import *`

```python
from math import *
# for example, what if there is a math.print() function?
# what happens when we then call print()?
```

# `collections` Module

In [101]:
from collections import Counter, defaultdict

- `Counter` : useful for counting hashable objects
- `defaultdict` : create dictionaries without checking keys
- `OrderedDict` : key,value pairs returned in order added
<br>

- others : https://docs.python.org/3.7/library/collections.html

# `collections` Module: `Counter`

In [102]:
c = Counter(['red', 'blue', 'red', 'green', 'blue', 'blue'])
c

Counter({'red': 2, 'blue': 3, 'green': 1})

In [103]:
c = Counter()
for word in ['red', 'blue', 'red', 'green', 'blue', 'blue']:
    c[word] += 1

In [104]:
c.most_common()

[('blue', 3), ('red', 2), ('green', 1)]

# `collections` Module Cont. : `defaultdict`

In [105]:
%xmode Minimal 
# reduce the amount printed when an exception is thrown

Exception reporting mode: Minimal


In [106]:
# create mapping from length of word to list of words
colors = ['red', 'blue', 'purple', 'gold', 'orange']
d = {}
for word in colors:
    d[len(word)].append(word)

KeyError: 3

In [107]:
d = {}
for word in colors:
    if len(word) in d:
        d[len(word)].append(word)
    else:
        d[len(word)] = [word]
d

{3: ['red'], 4: ['blue', 'gold'], 6: ['purple', 'orange']}

In [108]:
d = defaultdict(list)
for word in colors:
     d[len(word)].append(word)
d

defaultdict(list, {3: ['red'], 4: ['blue', 'gold'], 6: ['purple', 'orange']})

Defaultdict is a sub-class of the dictionary class that returns a dictionary-like object. The functionality of both dictionaries and defaultdict are almost same except for the fact that defaultdict never raises a KeyError. It provides a default value for the key that does not exists.

In [109]:
# Function to return a default
# values for keys that is not
# present
def def_value():
    return "Not Present"

d = defaultdict(def_value)
d["a"] = 1
d["b"] = 2
  
print(d["a"])
print(d["b"])
print(d["c"])

1
2
Not Present


# Contexts

- a context is like applying a scope with helper functions
- For example: open and write to a file

In [110]:
with open('tmp_context_example.txt','w') as f:
    f.write('test')

In [111]:
# instead of
f = open('tmp_context_example.txt','w')
f.write('test')
f.close() # this is easy to forget to do

In [112]:
# remove the example file we just created
%rm tmp_context_example.txt

# Python (Review?)

- Dynamic Typing
- Whitespace Formatting
- Basic Data Types
- Functions
- String Formatting
- Exceptions and Try-Except
- Truthiness
- Comparisons and Logical Operators
- Control Flow
- Assert
- Sorting
- List/Dict Comprehensions
- Importing Modules
- collections Module
- Object Oriented Programming

<br>
<br>

# <center>Questions?</center>
<br>
<br>

# Working with Data

Want to:
- transform and select data quickly (numpy)
<br>

- manipulate datasets: load, save, group, join, etc. (pandas)
<br>

- keep things organized (pandas)

# Intro to NumPy


<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/640px-NumPy_logo_2020.svg.png?1600616553332" width="200px">


Provides (from numpy.org):

- a powerful N-dimensional array object
<br>

- sophisticated (broadcasting) functions
<br>

- linear algebra and random number capabilities
<br>

- (Fourier transform, tools for integrating C/C++ and Fortran code, etc.)

# Python Dynamic Typing

In [6]:
x = 5
x = 'five'
type(x)
# this is dynamic typing, which means that the type of a variable can change during the execution of a program.

str

    - Note: still *strongly* typed
- Python is both a strongly typed and a dynamically typed language. 

## **Strong typing** means that variables do have a type and that the type matters when performing operations on a variable. 
## **Dynamic typing** means that the type of the variable is determined only during runtime.

In [3]:
x,y = 5,'five'
x+y

# this is strong typing, which means that the type of x and y must be the same.

TypeError: unsupported operand type(s) for +: 'int' and 'str'

# Python Dynamic Typing

<div align="center"><img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/cint_vs_pyint.png" width="500px"></div>
<br>
[PDHS Chap 2.](https://jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html)

- A C integer is essentially a label for a position in memory whose bytes encode an integer value. 
- A Python integer is a pointer to a position in memory containing all the Python object information, including the bytes that contain the integer value. 
    - **ob_refcnt**, a reference count that helps Python silently handle memory allocation and deallocation
    - **ob_type**, which encodes the type of the variable
    - **ob_size**, which specifies the size
    - **ob_digit**, which contains the actual integer value that we expect the Python variable to represent.
This extra information in the Python integer structure is what allows Python to be coded so freely and dynamically.


# NumPy Array vs Python List

## The NumPy array essentially contains a single pointer to one contiguous block of data. 
- This means that accessing or manipulating individual elements in a NumPy array is much faster than in a Python list. 
- single pointer means that NumPy arrays are more memory-efficient than Python lists. 

## The Python list, on the other hand, contains a pointer to a block of pointers, each of which in turn points to a full Python object like the Python integer we saw earlier. 
- This means that accessing or manipulating individual elements in a Python list is slower than in a NumPy array. 
- multiple pointers means that Python lists are more flexible than NumPy arrays.

## The advantage of the list is flexibility: because each list element is a full structure containing both data and type information, 
- Python list can be filled with data of any desired type. 
- Fixed-type NumPy-style arrays lack this flexibility, but are much more efficient for storing and manipulating data.

<div align="center"><img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/array_vs_list.png" width=700px></div>
<br>
<br>
<br>

[PDHS Chap 2.](https://jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html)

# Importing NumPy

Often imported as alias `np`

In [168]:
a = 10

In [169]:
a??

Type:        int
String form: 10
Docstring:  
int([x]) -> integer
int(x, base=10) -> integer

Convert a number or string to an integer, or return 0 if no arguments
are given.  If x is a number, return x.__int__().  For floating point
numbers, this truncates towards zero.

If x is not a number or if base is given, then x must be a string,
bytes, or bytearray instance representing an integer literal in the
given base.  The literal can be preceded by '+' or '-' and be surrounded
by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
Base 0 means to interpret the base from the string as an integer literal.
>>> int('0b100', base=0)
4

In [170]:
import numpy as np

np.random.randint(10,size=5) # generates 5 random integers between 0 and 9 (inclusive)
# np.random.randint(# of range (inclusive), size=number of random numbers to generate)
## # of range indicate the maximum value that can be generated. In this case, 9.

array([5, 9, 5, 6, 4])

# NumPy Datatypes

<font size="5">
    
```
bool_       Boolean (True or False) stored as a byte
int_        Default integer type (same as C long; normally either int64 or int32)
intc        Identical to C int (normally int32 or int64)
intp        Integer used for indexing (same as C ssize_t; normally either int32 or int64)
int8        Byte (-128 to 127)
int16       Integer (-32768 to 32767)
int32       Integer (-2147483648 to 2147483647)
int64       Integer (-9223372036854775808 to 9223372036854775807)
uint8       Unsigned integer (0 to 255)
uint16      Unsigned integer (0 to 65535)
uint32      Unsigned integer (0 to 4294967295)
uint64      Unsigned integer (0 to 18446744073709551615)
float_      Shorthand for float64.
float16     Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
float32     Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
float64     Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
complex_    Shorthand for complex128.
complex64   Complex number, represented by two 32-bit floats
complex128  Complex number, represented by two 64-bit floats
...
```
</font>

# NumPy Arrays

## numpy.array() function

- The `numpy.array()` function is used to create a NumPy array from a **Python list or tuple**.
- The `numpy.array()` function takes a **single argument**, which is the input list or tuple.

In [171]:
x = np.array([1,2,3]) # convert a python list to a numpy array
x

array([1, 2, 3])

In [172]:
type(x)

numpy.ndarray

In [173]:
# use dtype to show the datatype of the array
x.dtype

dtype('int64')

In [174]:
# np arrays can only contain one datatype and default to the most flexible type
x = np.array([1,'two',3]) 
# we don't mix data type in the python list and convert it to numpy array
x

array(['1', 'two', '3'], dtype='<U21')

In [175]:
x.dtype # it will give the unassigned data type due to mixing data type in the list

dtype('<U21')

In [176]:
# many different ways to create numpy arrays
np.zeros(5,dtype=float)

# np.zeros() creates an array of zeros with the specified size and data type
# np.zeros(# of elements (here is zeros), dtype=data type)

array([0., 0., 0., 0., 0.])

# NumPy Array Indexing

- For single indices, works the same as list

In [177]:
x = np.arange(1,6) 
# np.arange(start (element inclusive), stop (element exclusive), step (# of steps to skip))
x

array([1, 2, 3, 4, 5])

In [178]:
x[0], x[-1], x[-2], x[-4]

(1, 5, 4, 2)

# NumPy Array Slicing

In [179]:
x = np.arange(5) # note that in numpy it's arange (array range) instead of range
x

array([0, 1, 2, 3, 4])

In [180]:
# return first two items, start:end (exclusive)
x[0:2]

# x[index of first item (inclusive) : index of last item + 1 (exclusive)]
# x[0 (index of first item => 0) : 2 (index of second item + 1 => 1)]

array([0, 1])

In [181]:
# missing start implies position 0
x[:4]

# x[: index of last item + 1] => it will return all the elements from the start of array to the index of last item + 1

array([0, 1, 2, 3])

In [182]:
# missing end implies length of array
x[2:]

# x[index of first item: ] => it will return all the elements from the index of first item to the end of the array

array([2, 3, 4])

In [183]:
# return last 3 items
x[-3:] # - means reverse order

# x[-3:] returns array without first 3 items

array([2, 3, 4])

In [184]:
x[: -2]

# it return the array without the last two elements

array([0, 1, 2])

# NumPy Array Slicing with Steps

In [185]:
x

array([0, 1, 2, 3, 4])

In [186]:
# return every other item from position 1 to 4 exclusive
# start:end:step_size
x[1:4:1] 

# x[start (first item index): end (last item index + 1): step_size]

array([1, 2, 3])

# Reverse array with step-size of -1

In [187]:
x

array([0, 1, 2, 3, 4])

In [188]:
x[::-1]

# x[::-1] means to reverse the order of the elements in the array x with step 1

array([4, 3, 2, 1, 0])

In [189]:
x[::-2] # reverse the array with taking 2 steps

array([4, 2, 0])

# NumPy Fancy Indexing

- Accessing multiple, non-consecutive indices at once using a list

In [190]:
x = np.arange(5,10)

# np.arange(first item, last item+1, step size)

x

array([5, 6, 7, 8, 9])

In [191]:
x[[0,3]]

# x[[item 1 index : item 2 index .....]] => it can extract a sublist from the numpy array based on the given index range and step.

array([5, 8])

In [192]:
x[[0,2,-1]]

# there is no index rule in numpy indexing. It is just a list of indices.


array([5, 7, 9])

# Boolean Indexing using a Boolean Mask

## it selects everything in the array and returns a new array with only the values that correspond to the True values in the mask.
## The mask is a boolean array with the same shape as the original array.

In [193]:
x
# x is the numpy array [5, 6, 7, 8, 9]

array([5, 6, 7, 8, 9])

In [194]:
# Which indices have a value divisible by 2?
# mod operator % returns remainder of division
x%2 == 0

# it will return the boolean array with True for indices where the condition is True

array([False,  True, False,  True, False])

In [195]:
# Which values are divisible by 2?
x[x%2 == 0]

# x[condition expression] will return the array of values of x where the condition expression is True. 
# In this case, the condition expression is x%2 == 0, which checks if the remainder of x divided by 2 is 0.

array([6, 8])

In [196]:
# Which values are greater than 6?
x[x >= 2]

array([5, 6, 7, 8, 9])

# Boolean Indexing And Bitwise Operators

In [197]:
x

array([5, 6, 7, 8, 9])

In [198]:
(x%2 == 0)

# (condition expression) will return boolean array with True for elements where condition is True and False for elements where condition is False.

array([False,  True, False,  True, False])

In [199]:
(x > 6)

array([False, False,  True,  True,  True])

## mid-term notice

In [200]:
x

array([5, 6, 7, 8, 9])

In [201]:
# Which values are divisible by 2 AND greater than 6?
# 'and' expexts both elements to be boolean, not arrays of booleans!
(x%2 == 0) and (x > 6) # each expression returns boolean array

# boolean array cannot be combined by "and" "or" "not"
# boolean array can be combined by "&" "|" "~"

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [202]:
# "and", "or", and "not" for logical operations on individual boolean values, not for element-wise operations on arrays or lists.

a = 5
b = 10

print(a < b and b > a)

True


In [203]:
x

array([5, 6, 7, 8, 9])

In [204]:
# & compares each element pairwise
(x%2 == 0) & (x > 6) # (condition1 & condition2) acts as boolean numpy array and returns True or False for each element in array.

# it can return a boolean array with True for each element that satisfies both conditions and False for those that don't.

array([False, False, False,  True, False])

In [205]:
x[np.array([False, False, False,  True, False])]

# it returns the elements of x that are not False with format of numpy array

array([8])

In [206]:
x[(x%2 == 0) & (x > 6)] 

# list[(condition)] will return a array of items that satisfy the condition.

array([8])

# Boolean Indexing And Bitwise Operators

- and : `&` (ampersand)

In [207]:
# Which values are even AND greater than 6?
x[(x%2 == 0) & (x > 6)]

# & is the intersection operator, which means it returns only the values that are present in both arrays.

array([8])

- or : `|` (pipe)

In [208]:
# which values are even OR greater than 6?
x[(x%2 == 0) | (x > 6)]

# | is the OR operator, which means it returns the values that are either even or greater than 6 (whole set)

array([6, 7, 8, 9])

- not : `~` (tilde)

In [209]:
( (x%2 == 0) | (x > 6) )

array([False,  True,  True,  True,  True])

In [210]:
~( (x%2 == 0) | (x > 6) )

# ~ is NOT operator, it returns the boolean value of the opposite of the expression inside the parentheses.

array([ True, False, False, False, False])

In [211]:
# which values are NOT (even OR greater than 6)
x[~( (x%2 == 0) | (x > 6) )]

array([5])

- see [PDHS](https://jakevdp.github.io/PythonDataScienceHandbook/02.06-boolean-arrays-and-masks.html) for more info

# Indexing Review

- standard array indexing (including reverse/negative)
<br>

- slicing [start:end:step-size]
<br>

- fancy indexing (list/array of indices)
<br>

- boolean indexing (list/array of booleans)

# Multidimensional Lists

In [213]:
x = [[1,2,3],[4,5,6]] # list of lists

# [[list1], [list2]] represent 2 sub-lists in the original list

x

[[1, 2, 3], [4, 5, 6]]

In [214]:
# return first row
x[0]

# x[index for rows, index for columns]

[1, 2, 3]

In [215]:
# return first row, second column
x[1][2] 

6

In [216]:
# return second column?
[row[1] for row in x]

[2, 5]

# NumPy Multidimensional Arrays

In [217]:
# To convert the list of lists into a 2D numpy array, we can use the numpy.array() function:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [218]:
x[0,1] # first row, second column

# x[index for row item, index for column item]

2

In [160]:
x[:,1] # first row

# x[:, column indexing] will return all the rows with the specified column index.

array([2, 5])

In [219]:
x[0,:] # first row (first to last column)

# x[row indexing, :] will return all the columns of the specified row.

array([1, 2, 3])

In [220]:
x[:,1] # second column (first to last row)

array([2, 5])

# NumPy Array Attributes

In [226]:
x = np.array([[1,2,3],[4,5,6]])

x

array([[1, 2, 3],
       [4, 5, 6]])

In [227]:
x.ndim # number of dimensions

# array.ndim is the number of dimensions of the array. 
# In this case, x has 2 dimensions, which is the row and column dimension. 

2

In [228]:
x.shape # shape in each dimension

# shape of row by column

(2, 3)

In [166]:
x.size # total number of elements

6

# NumPy Operations (UFuncs)

In [230]:
x = [1,2,3]
y = [4,5,6]

In [231]:
x+y

# since x and y are lists, operating addition will only concatenate them but not perform any arithmetic operation.

[1, 2, 3, 4, 5, 6]

In [232]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [170]:
x+y

# Once we convert the list to a numpy array, we can perform mathematical operations on it (one to one) into a single row.

array([5, 7, 9])

In [235]:
%time sum(range(0,int(1e8)))

CPU times: user 739 ms, sys: 11.4 ms, total: 750 ms
Wall time: 778 ms


4999999950000000

In [236]:
%time np.arange(0,int(1e8)).sum()

CPU times: user 78.2 ms, sys: 127 ms, total: 205 ms
Wall time: 267 ms


4999999950000000

# NumPy Broadcasting

Allows for vectorized computation on arrays of different sizes

In [237]:
# square every element in a list
x = [1,2,3]

In [239]:
x**2

# a python list will not be operated by the ** operator

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [240]:
# square every element in a numpy array
x = np.array([1,2,3])

In [242]:
x**2

# numpy array can operate each element of the array

array([1, 4, 9])

## Numpy Broadcasting

### a numpy array is a high-dimensional array that can be used to perform mathematical operations on vectors and matrices.
### since an array is a **higher dimensional object**, it can be mathematically operated on with **another array of the same shape or a scalar value**

In [245]:
a = np.array([1.0, 2.0, 3.0]) # it is a 1D array which is higher dimensional than a scalar or a value.
b = 2.0 # it is a scalar value object.
a * b # an array (higher dimension) can be multiplied by a scalar value (lower dimension).

array([2., 4., 6.])

is equivalent to 

In [246]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

# NumPy `random` Submodule

Provides many random sampling functions

In [247]:
from numpy.random import seed, randn

In [250]:
seed(1991)
# setting a seed can help ensure that the results are reproducible

In [266]:
randn(10)

array([-1.0312311 ,  0.89968648, -0.58933691,  2.01752653,  1.68102644,
        0.40037836, -0.18176497,  1.53308122, -0.211595  ,  1.3531789 ])

`from numpy.random import ...`

- `rand` : random floats

- `randint` : random integers

- `randn` : standard normal distribution

- `permutation` : random permutation

- `normal` : Gaussian normal distribution

- `seed` : seed the random generator

<br>
<br>

# <center>Questions?</center>
<br>
<br>